---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateways-options
  namespace: default
  labels:
    app: is-spinnaker-gateway
data:
  options_0: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 0,
        "ip": "10.20.6.0",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "initial_config": "/etc/is-spinnaker-gateway/cameras/camera_0.json"
      }
    }
  options_1: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 1,
        "ip": "10.20.6.1",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "initial_config": "/etc/is-spinnaker-gateway/cameras/camera_1.json"
      }
    }
  options_2: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 2,
        "ip": "10.20.6.2",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "initial_config": "/etc/is-spinnaker-gateway/cameras/camera_2.json"
      }
    }
  options_3: |-
    {
      "rabbitmq_uri": "amqp://rabbitmq.default",
      "zipkin_uri" : "http://zipkin.default:9411",
      "camera": {
        "id": 3,
        "ip": "10.20.6.3",
        "algorithm": "BILINEAR",
        "onboard_color_processing": false,
        "packet_size": 1400,
        "packet_delay": 6000,
        "packet_resend": true,
        "packet_resend_timeout": 100,
        "packet_resend_max_requests": 10000,
        "reverse_x": false,
        "use_turbojpeg": true,
        "initial_config": "/etc/is-spinnaker-gateway/cameras/camera_3.json"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateways-initial-configs
  namespace: default
  labels:
    app: is-spinnaker-gateway
data:
  camera_0: |-
    {
      "sampling": {
        "frequency": 10.0
      },
      "image": {
        "color_space": {
          "value": "RGB"
        },
        "format": {
          "format": "JPEG",
          "compression": 0.8
        }
      },
      "camera": {
        "gain": {
          "automatic": true,
          "ratio": 0
        }
      }
    }

  camera_1: |-
    {
      "sampling": {
        "frequency": 10.0
      },
      "image": {
        "color_space": {
          "value": "RGB"
        },
        "format": {
          "format": "JPEG",
          "compression": 0.8
        }
      },
      "camera": {
        "gain": {
          "automatic": true,
          "ratio": 0
        }
      }
    }

  camera_2: |-
    {
      "sampling": {
        "frequency": 10.0
      },
      "image": {
        "color_space": {
          "value": "RGB"
        },
        "format": {
          "format": "JPEG",
          "compression": 0.8
        }
      },
      "camera": {
        "gain": {
          "automatic": true,
          "ratio": 0
        }
      }
    }

  camera_3: |-
    {
      "sampling": {
        "frequency": 10.0
      },
      "image": {
        "color_space": {
          "value": "RGB"
        },
        "format": {
          "format": "JPEG",
          "compression": 0.8
        }
      },
      "camera": {
        "gain": {
          "automatic": true,
          "ratio": 0
        }
      }
    }
